# Copyright (C) 2026 NV Access Limited, Abdel
# This file is covered by the GNU General Public License.
# See the file COPYING for more details.

from collections.abc import MutableMapping, MutableSequence
import argparse
import ast
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, cast

import tomlkit

logger: logging.Logger = logging.getLogger("syncAddon")


def buildArgParser() -> argparse.ArgumentParser:
	"""Build and configure the command-line argument parser.

	:return: Configured ArgumentParser object.
	"""
	parser: argparse.ArgumentParser = argparse.ArgumentParser(
		description="Non-destructive industrial update tool for NVDA Add-ons.",
	)
	parser.add_argument(
		"-ad", "--addon-dir",
		dest="addonDir",
		default=None,
		help="Path to the root directory of the add-on to update (defaults to current directory).",
	)
	parser.add_argument(
		"-td", "--template-dir",
		dest="templateDir",
		default=None,
		help="Path to a local directory containing the NVDA AddonTemplate to use instead of fetching it via Git.",
	)
	parser.add_argument(
		"-dr", "--dry-run",
		dest="dryRun",
		action="store_true",
		help="Simulate execution without modifying any files.",
	)
	parser.add_argument(
		"-s", "--skip-backup",
		dest="skipBackup",
		action="store_true",
		help="Disable safety automatic project backup.",
	)
	return parser


def parseAstDict(node: ast.Dict) -> dict[str, Any]:
	"""Extract key-value pairs from an AST Dict node.

	:param node: The ast.Dict node to parse.
	:return: A dictionary containing the extracted keys and values.
	"""
	extracted: dict[str, Any] = {}
	keyNode: ast.expr | None
	valNode: ast.expr
	for keyNode, valNode in zip(node.keys, node.values):
		if keyNode is None:
			continue
		key: Any = getattr(keyNode, "value", None)
		if isinstance(valNode, ast.Call) and getattr(valNode.func, "id", None) == "_":
			valNode = valNode.args[0]
		val: Any = getattr(valNode, "value", None)
		if key is not None:
			extracted[key] = val
	return extracted


def parseAstKeywords(keywords: list[ast.keyword]) -> dict[str, Any]:
	"""Extract key-value pairs from a list of AST keyword nodes.

	:param keywords: The list of ast.keyword nodes to parse.
	:return: A dictionary containing the extracted keys and values.
	"""
	extracted: dict[str, Any] = {}
	keyword: ast.keyword
	for keyword in keywords:
		key: str | None = keyword.arg
		valNode: ast.expr = keyword.value
		if isinstance(valNode, ast.Call) and getattr(valNode.func, "id", None) == "_":
			valNode = valNode.args[0]
		val: Any = getattr(valNode, "value", None)
		if key is not None:
			extracted[key] = val
	return extracted


def usesOsModule(node: ast.AST) -> bool:
	"""Check recursively if an AST node contains an actual reference to the 'os' module.

	:param node: The AST node to inspect.
	:return: True if the node references 'os', False otherwise.
	"""
	child: ast.AST
	for child in ast.walk(node):
		if isinstance(child, ast.Name) and child.id == "os":
			return True
	return False


def formatAuthorList(rawAuthors: str) -> tomlkit.items.Array:
	"""Convert a comma-separated string of authors into a tomlkit multiline array.

	Omits empty 'email' fields to prevent validation errors during 'uv run scons'
	and PEP 621 metadata compliance checks.

	:param rawAuthors: The raw authors string (e.g., "Author Name <email@example.com>, Another").
	:return: A tomlkit.items.Array object containing inline tables.
	"""
	authorsList: tomlkit.items.Array = tomlkit.array()
	authorsList.multiline(True)

	parts: list[str] = [p.strip() for p in rawAuthors.split(",") if p.strip()]

	part: str
	for part in parts:
		regexMatch: re.Match[str] | None = re.match(r"^(.*?)\s*<(.*?)>$", part)
		if regexMatch:
			name: str = regexMatch.group(1).strip()
			email: str = regexMatch.group(2).strip()
			authorTable: tomlkit.items.InlineTable = tomlkit.inline_table()
			authorData: dict[str, str] = {"name": name}
			# Omit empty email to prevent validation failures in tools like uv/scons
			if email:
				authorData["email"] = email
			authorTable.update(authorData)
			authorsList.append(authorTable)
		elif part:
			authorTable = tomlkit.inline_table()
			# Omit email key entirely if no email address was provided
			authorTable.update({"name": part})
			authorsList.append(authorTable)

	return authorsList


def fixTomlIndentation(tomlText: str) -> str:
	"""Replace leading 4-space indentations with a tab inside maintainers/authors array blocks.

	:param tomlText: The raw TOML string generated by tomlkit.
	:return: The TOML string with strictly enforced tab indentation.
	"""
	lines: list[str] = tomlText.splitlines(keepends=True)
	fixedLines: list[str] = []
	inTargetArray: bool = False

	line: str
	for line in lines:
		stripped: str = line.strip()
		if re.match(r"^(?:maintainers|authors)\s*=\s*\[", stripped):
			inTargetArray = True
			fixedLines.append(line)
			continue

		if inTargetArray:
			if stripped == "]":
				inTargetArray = False
				fixedLines.append(line)
			else:
				fixedLines.append(re.sub(r"^ {4}", "\t", line))
		else:
			fixedLines.append(line)

	return "".join(fixedLines)


def createPyprojectFromTemplate(templatePath: Path, metadata: dict[str, Any]) -> tomlkit.TOMLDocument:
	"""Create a new pyproject.toml document based on the official template, preserving tab indentation.

	:param templatePath: Path to the reference template pyproject.toml file.
	:param metadata: Extracted metadata dictionary from legacy buildVars/manifest.
	:return: A tomlkit TOMLDocument adhering to template tab formatting and populated with metadata.
	"""
	with templatePath.open("r", encoding="utf-8") as f:
		doc: tomlkit.TOMLDocument = tomlkit.parse(f.read())

	if "project" not in doc:
		doc["project"] = tomlkit.table()

	projectSection: Any = doc["project"]

	if "addon_name" in metadata and metadata["addon_name"]:
		projectSection["name"] = metadata["addon_name"]

	if "addon_summary" in metadata and metadata["addon_summary"]:
		projectSection["description"] = metadata["addon_summary"]

	addonUrl: str = str(metadata.get("addon_url", "")).strip()
	if addonUrl:
		if "urls" not in projectSection:
			projectSection["urls"] = tomlkit.table()
		projectSection["urls"]["Repository"] = addonUrl

	if "addon_author" in metadata and metadata["addon_author"]:
		projectSection["maintainers"] = formatAuthorList(metadata["addon_author"])

	return doc


def cleanupPlaceholderAuthors(projectSection: dict[str, Any]) -> None:
	"""Remove NV Access placeholder entries from authors and maintainers fields in-place.

	:param projectSection: The project table/dictionary within the TOML structure.
	:return: None
	"""
	field: str
	for field in ["authors", "maintainers"]:
		if field in projectSection and isinstance(projectSection[field], (list, MutableSequence)):
			tomlList: Any = projectSection[field]
			i: int
			for i in range(len(tomlList) - 1, -1, -1):
				item: Any = tomlList[i]
				name: Any = item.get("name", "") if hasattr(item, "get") else ""
				if not name and isinstance(item, dict):
					name = item.get("name", "")

				if str(name).strip().lower() in ["nv access", "nvaccess"]:
					tomlList.pop(i)


def getBasePackageName(dependencyString: str) -> str:
	"""Extract base package name robustly (handles !=, <=, ~=, @ URLs, markers, etc.).

	:param dependencyString: The raw dependency string.
	:return: The normalized base package name in lowercase.
	"""
	regexMatch: re.Match[str] | None = re.match(r"^[A-Za-z0-9][A-Za-z0-9._-]*", dependencyString.strip())
	return regexMatch.group(0).lower() if regexMatch else dependencyString.strip().lower()


def replaceAstRange(templateLines: list[str], replacements: dict[tuple[int, int], str]) -> None:
	"""Apply AST line replacements on a line-by-line list in reverse order.

	:param templateLines: The list of lines representing the file content.
	:param replacements: A dictionary mapping (start_line, end_line) tuples to the replacing string.
	:return: None
	"""
	sortedRanges: list[tuple[int, int]] = sorted(replacements.keys(), key=lambda x: x[0], reverse=True)
	start: int
	end: int
	for start, end in sortedRanges:
		templateLines[start:end] = [replacements[(start, end)]]


def mergeDependencyLists(projList: list[Any], tplList: list[Any]) -> list[Any]:
	"""Intelligently merge two dependency lists by updating package versions based on base names.

	Preserves custom user dependencies while replacing existing template tools with their newer versions.

	:param projList: The existing project's dependency list.
	:param tplList: The template's dependency list.
	:return: A merged list with updated versions and preserved custom items.
	"""
	projIndexByBase: dict[str, int] = {}
	idx: int
	item: Any
	for idx, item in enumerate(projList):
		if isinstance(item, str):
			base: str = getBasePackageName(item)
			projIndexByBase[base] = idx

	merged: list[Any] = list(projList)

	tplItem: Any
	for tplItem in tplList:
		if isinstance(tplItem, str):
			tplBase: str = getBasePackageName(tplItem)
			if tplBase in projIndexByBase:
				targetIdx: int = projIndexByBase[tplBase]
				merged[targetIdx] = tplItem
			else:
				merged.append(tplItem)
		else:
			if tplItem not in merged:
				merged.append(tplItem)

	return merged


def deepMergeDicts(dictProj: dict[str, Any], dictTpl: dict[str, Any]) -> dict[str, Any]:
	"""Recursively merges dictTpl into dictProj.

	:param dictProj: The original dictionary to be updated.
	:param dictTpl: The template dictionary whose values will be merged into dictProj.
	:return: The updated dictProj with merged values from dictTpl.
	"""
	key: str
	value: Any
	for key, value in dictTpl.items():
		if key in dictProj:
			projVal: Any = dictProj[key]
			if isinstance(projVal, MutableMapping) and isinstance(value, MutableMapping):
				deepMergeDicts(projVal, value)
			elif isinstance(projVal, MutableSequence) and isinstance(value, MutableSequence):
				dictProj[key] = mergeDependencyLists(list(projVal), list(value))
			else:
				pass
		else:
			dictProj[key] = value
	return dictProj


def extractBuildvarsMetadata(filePath: str | Path) -> tuple[dict[str, Any], dict[str, tuple[ast.AST, str]]]:
	"""Extract metadata and raw assignment expressions along with AST nodes from buildVars.py safely.

	:param filePath: The path to the buildVars.py file.
	:return: A tuple containing two dictionaries: metadata and globalVars mapping var_name -> (ast_node, unparsed_expr).
	"""
	filePathObj: Path = Path(filePath)
	if not filePathObj.exists():
		return {}, {}

	with filePathObj.open("r", encoding="utf-8") as f:
		try:
			tree: ast.AST = ast.parse(f.read())
		except SyntaxError as syntaxErr:
			logger.error("Syntax error while reading %s: %s", filePathObj, syntaxErr)
			return {}, {}

	metadata: dict[str, Any] = {}
	globalVars: dict[str, tuple[ast.AST, str]] = {}
	topLevelVars: set[str] = {
		"pythonSources",
		"excludedFiles",
		"baseLanguage",
		"markdownExtensions",
		"brailleTables",
		"symbolDictionaries",
		"speechDictionaries",
	}

	node: ast.AST
	for node in ast.walk(tree):
		if isinstance(node, ast.Assign) and len(node.targets) == 1:
			target: ast.expr = node.targets[0]
			if not isinstance(target, ast.Name):
				continue
			varName: str = target.id

			if varName == "addon_info":
				if isinstance(node.value, ast.Dict):
					metadata.update(parseAstDict(node.value))
				elif isinstance(node.value, ast.Call) and getattr(node.value.func, "id", None) == "AddonInfo":
					metadata.update(parseAstKeywords(node.value.keywords))
			elif varName in topLevelVars:
				globalVars[varName] = (node.value, ast.unparse(node.value))
		elif isinstance(node, ast.AnnAssign):
			if isinstance(node.target, ast.Name) and node.target.id in topLevelVars:
				if node.value is not None:
					globalVars[node.target.id] = (node.value, ast.unparse(node.value))

	return metadata, globalVars


def mergePyprojectToml(projPath: str | Path, tplPath: str | Path, metadata: dict[str, Any], dryRun: bool = False) -> str:
	"""Merge template pyproject.toml configuration into the developer's file.

	:param projPath: Path to the existing pyproject.toml file.
	:param tplPath: Path to the template pyproject.toml file.
	:param metadata: Dictionary containing legacy metadata values from buildVars.py.
	:param dryRun: If True, simulate the merge without writing changes to disk.
	:return: A string indicating the result of the merge operation.
	"""
	templatePathObj: Path = Path(tplPath)
	projectPathObj: Path = Path(projPath)

	if not templatePathObj.exists():
		return "skipped (no template found)"

	if not projectPathObj.exists():
		try:
			projData: tomlkit.TOMLDocument = createPyprojectFromTemplate(templatePathObj, metadata)
			if not dryRun:
				tomlOutput: str = fixTomlIndentation(tomlkit.dumps(projData))
				projectPathObj.parent.mkdir(parents=True, exist_ok=True)
				with projectPathObj.open("w", encoding="utf-8") as f:
					f.write(tomlOutput)
				logger.info("Created missing pyproject.toml at %s", projectPathObj)
			return "created from template"
		except Exception as exceptionObj:
			logger.error("Failed to create pyproject.toml: %s", exceptionObj)
			return f"failed to create from template ({str(exceptionObj)})"

	try:
		with projectPathObj.open("r", encoding="utf-8") as f:
			projData = tomlkit.parse(f.read())
		with templatePathObj.open("r", encoding="utf-8") as f:
			tplData: tomlkit.TOMLDocument = tomlkit.parse(f.read())

		wasOriginallyNvaccess: bool = False
		if "project" in projData:
			field: str
			for field in ["authors", "maintainers"]:
				if field in projData["project"] and isinstance(projData["project"][field], (list, MutableSequence)):
					item: Any
					for item in projData["project"][field]:
						name: Any = item.get("name", "") if hasattr(item, "get") else ""
						if not name and isinstance(item, dict):
							name = item.get("name", "")
						if str(name).strip().lower() in ["nv access", "nvaccess"]:
							wasOriginallyNvaccess = True
							break

		projDeps: list[Any] = []
		if "project" in projData and "dependencies" in projData["project"]:
			projDeps = list(projData["project"]["dependencies"])
			del projData["project"]["dependencies"]

		mergedData: dict[str, Any] = deepMergeDicts(cast(dict[str, Any], projData), cast(dict[str, Any], tplData))

		if "project" in mergedData:
			projectSection: dict[str, Any] = mergedData["project"]

			if not wasOriginallyNvaccess:
				cleanupPlaceholderAuthors(projectSection)

			if isinstance(projectSection.get("dependencies"), (list, MutableSequence)):
				tplDeps: list[Any] = projectSection["dependencies"]
				tplBases: set[str] = {getBasePackageName(d) for d in tplDeps}

				groupBases: set[str] = set()
				if "dependency-groups" in mergedData and isinstance(mergedData["dependency-groups"], MutableMapping):
					grp: Any
					for grp in mergedData["dependency-groups"].values():
						if isinstance(grp, (list, MutableSequence)):
							grpItem: Any
							for grpItem in grp:
								if isinstance(grpItem, str):
									groupBases.add(getBasePackageName(grpItem))

				legacyToolingBases: set[str] = {
					"pre-commit",
					"scons",
					"markdown",
					"nh3",
					"crowdin-api-client",
					"lxml",
					"mdx_truly_sane_lists",
					"markdown-link-attr-modifier",
					"mdx-gh-links",
					"uv",
					"ruff",
					"prek",
					"pyright",
				}

				dep: Any
				for dep in projDeps:
					base: str = getBasePackageName(dep)
					isInTemplate: bool = base in tplBases or base in groupBases
					isDroppedTooling: bool = base in legacyToolingBases and not isInTemplate

					if not isInTemplate and not isDroppedTooling:
						tplDeps.append(dep)

		if not dryRun:
			tomlOutput = fixTomlIndentation(tomlkit.dumps(cast(tomlkit.TOMLDocument, mergedData)))
			with projectPathObj.open("w", encoding="utf-8") as f:
				f.write(tomlOutput)
		return "merged intelligently (tomlkit)"
	except Exception as exceptionObj:
		logger.error("Failed to merge pyproject.toml: %s", exceptionObj)
		return f"failed to merge ({str(exceptionObj)})"


def mergeBuildvarsFile(
	projPath: str | Path,
	tplPath: str | Path,
	metadata: dict[str, Any],
	globalVars: dict[str, tuple[ast.AST, str]],
	dryRun: bool = False,
) -> str:
	"""Merge template buildVars.py using precise AST range tracking to prevent multiline leaks.

	:param projPath: Path to the existing buildVars.py file.
	:param tplPath: Path to the template buildVars.py file.
	:param metadata: Dictionary containing metadata values to update.
	:param globalVars: Dictionary containing global variables mapping var_name -> (ast_node, unparsed_expr).
	:param dryRun: If True, simulate the merge without writing changes to disk.
	:return: A string indicating the result of the merge operation.
	"""
	templatePathObj: Path = Path(tplPath)
	projectPathObj: Path = Path(projPath)

	if not templatePathObj.exists():
		return "failed (no template found)"

	with templatePathObj.open("r", encoding="utf-8") as f:
		tplContent: str = f.read()

	try:
		tree: ast.AST = ast.parse(tplContent)
	except SyntaxError as syntaxErr:
		return f"failed (template syntax error: {syntaxErr})"

	tplLines: list[str] = tplContent.splitlines(keepends=True)
	replacements: dict[tuple[int, int], str] = {}
	requiresOsImport: bool = False

	node: ast.AST
	for node in ast.walk(tree):
		if isinstance(node, ast.Call) and getattr(node.func, "id", None) == "AddonInfo":
			kw: ast.keyword
			for kw in node.keywords:
				if kw.arg in metadata:
					key: str = kw.arg
					val: Any = metadata[key]
					formattedVal: str
					if val is None:
						formattedVal = "None"
					elif isinstance(val, str):
						isTranslatable: bool = key in ["addon_summary", "addon_description", "addon_changelog"]
						formattedVal = f"_({val!r})" if isTranslatable else repr(val)
					else:
						formattedVal = str(val)

					if kw.end_lineno is not None:
						lineContent: str = tplLines[kw.lineno - 1]
						indent: str = lineContent[: len(lineContent) - len(lineContent.lstrip())]
						replacements[(kw.lineno - 1, kw.end_lineno)] = f"{indent}{key}={formattedVal},\n"

		elif isinstance(node, ast.Assign) and len(node.targets) == 1:
			target: ast.expr = node.targets[0]
			if isinstance(target, ast.Name) and target.id in globalVars:
				key = target.id
				valNode: ast.AST
				valExpression: str
				valNode, valExpression = globalVars[key]
				if usesOsModule(valNode):
					requiresOsImport = True
				if node.end_lineno is not None:
					lineContent = tplLines[node.lineno - 1]
					indent = lineContent[: len(lineContent) - len(lineContent.lstrip())]
					replacements[(node.lineno - 1, node.end_lineno)] = (
						f"{indent}{key} = {valExpression}\n"
					)

		elif isinstance(node, ast.AnnAssign):
			if isinstance(node.target, ast.Name) and node.target.id in globalVars:
				key = node.target.id
				valNode, valExpression = globalVars[key]
				if usesOsModule(valNode):
					requiresOsImport = True
				if node.end_lineno is not None:
					lineContent = tplLines[node.lineno - 1]
					indent = lineContent[: len(lineContent) - len(lineContent.lstrip())]
					typeStr: str = ast.unparse(node.annotation)
					replacements[(node.lineno - 1, node.end_lineno)] = (
						f"{indent}{key}: {typeStr} = {valExpression}\n"
					)

	replaceAstRange(tplLines, replacements)

	if requiresOsImport:
		hasOsImport: bool = any("import os" in line for line in tplLines[:15])
		if not hasOsImport:
			tplLines.insert(0, "import os\n")

	if not dryRun:
		with projectPathObj.open("w", encoding="utf-8") as f:
			f.writelines(tplLines)
	return "merged & structured (AST verified)"


def runSynchronization(tempDir: str, addonDir: str, dryRun: bool) -> None:
	"""Synchronizes template machinery files from the temporary workspace into the target directory.

	:param tempDir: Path to the local temporary directory containing the template files.
	:param addonDir: Path to the target add-on root directory.
	:param dryRun: If True, simulate the sync without writing changes to disk.
	:return: None
	"""
	logger.info("Synchronizing template machinery files...")

	protectedElements: set[str] = {
		"readme.md",
		"changelog.md",
		"addontemplate.egg-info",
		".github/workflows/unittests.yml",
		"addon",
		".git",
		"__pycache__",
		".venv",
		"docs",
		".ruff_cache",
		"tests",
	}

	ignoreFilePath: str = os.path.join(addonDir, ".addonmergeignore")
	if os.path.exists(ignoreFilePath):
		logger.info("Reading local custom exclusions from .addonmergeignore...")
		try:
			with open(ignoreFilePath, "r", encoding="utf-8") as f:
				line: str
				for line in f:
					cleanLine: str = line.strip().replace("\\", "/").lower()
					if cleanLine and not cleanLine.startswith("#"):
						protectedElements.add(cleanLine)
		except Exception as exceptionObj:
			logger.warning("Failed to parse .addonmergeignore (%s)", exceptionObj)

	syncReport: list[str] = []

	def addReportEntry(entry: str) -> None:
		"""Add an entry to syncReport ensuring no duplicates exist.

		:param entry: The status report line to record.
		:return: None
		"""
		if entry not in syncReport:
			syncReport.append(entry)

	def inspectAndCopyDirectory(srcDir: str, dstDir: str) -> None:
		"""Inspect directory recursively for protected elements and copy non-protected files.

		:param srcDir: Path to the source directory to inspect.
		:param dstDir: Path to the destination target directory.
		:return: None
		"""
		root: str
		dirs: list[str]
		files: list[str]
		for root, dirs, files in os.walk(srcDir):
			relDir: str = os.path.relpath(root, tempDir)

			dirsToCopy: list[str] = []
			dirName: str
			for dirName in dirs:
				relPath: str = dirName if relDir == "." else os.path.join(relDir, dirName)
				relPathNormalized: str = relPath.replace("\\", "/").lower()
				if relPathNormalized in protectedElements:
					displayPath: str = relPath.replace("\\", "/")
					addReportEntry(f"- **{displayPath}/**: skipped (protected scope)")
				else:
					dirsToCopy.append(dirName)
			dirs[:] = dirsToCopy

			relDst: str = os.path.relpath(root, srcDir)
			targetRoot: str = os.path.join(dstDir, relDst)

			fileName: str
			for fileName in files:
				relPath = fileName if relDir == "." else os.path.join(relDir, fileName)
				relPathNormalized = relPath.replace("\\", "/").lower()
				if relPathNormalized in protectedElements:
					displayPath = relPath.replace("\\", "/")
					addReportEntry(f"- **{displayPath}**: skipped (protected scope)")
				else:
					if not dryRun:
						srcFile: str = os.path.join(root, fileName)
						dstFile: str = os.path.join(targetRoot, fileName)
						os.makedirs(os.path.dirname(dstFile), exist_ok=True)
						shutil.copy2(srcFile, dstFile)

	item: str
	for item in os.listdir(tempDir):
		itemNormalized: str = item.lower()
		if itemNormalized in protectedElements:
			addReportEntry(f"- **{item}**: skipped (protected scope)")
			continue

		if item in ["buildVars.py", "pyproject.toml"]:
			continue

		srcItem: str = os.path.join(tempDir, item)
		dstItem: str = os.path.join(addonDir, item)

		try:
			if os.path.isdir(srcItem):
				inspectAndCopyDirectory(srcItem, dstItem)
				addReportEntry(f"- **{item}/**: merged safely")
			else:
				if not dryRun:
					shutil.copy2(srcItem, dstItem)
				addReportEntry(f"- **{item}**: synchronized")
		except Exception as exceptionObj:
			addReportEntry(f"- **{item}**: failed ({str(exceptionObj)})")

	logger.info("Processing structural configuration merges...")
	templateBuildvars: str = os.path.join(tempDir, "buildVars.py")
	templatePyproject: str = os.path.join(tempDir, "pyproject.toml")

	oldBuildvars: str = os.path.join(addonDir, "buildVars.py")
	oldPyproject: str = os.path.join(addonDir, "pyproject.toml")

	buildvarsMetadata: dict[str, Any]
	buildvarsGlobals: dict[str, tuple[ast.AST, str]]
	buildvarsMetadata, buildvarsGlobals = extractBuildvarsMetadata(oldBuildvars)
	addonName: Any = buildvarsMetadata.get("addon_name", os.path.basename(addonDir))

	buildvarsStatus: str = mergeBuildvarsFile(oldBuildvars, templateBuildvars, buildvarsMetadata, buildvarsGlobals, dryRun)
	pyprojectStatus: str = mergePyprojectToml(oldPyproject, templatePyproject, buildvarsMetadata, dryRun)

	logger.info("=" * 50)
	logger.info("UPDATE REPORT")
	logger.info("=" * 50)
	logger.info("Add-on: %s", addonName)
	logger.info("\nTemplate synchronization:")
	entry: str
	for entry in sorted(syncReport):
		logger.info("  %s", entry)
	logger.info(
		"\nConfiguration files:\n  - **buildVars.py**: %s\n  - **pyproject.toml**: %s",
		buildvarsStatus,
		pyprojectStatus,
	)


def main() -> None:
	"""Execute main CLI entry point for the NVDA Add-on update tool.

	:return: None
	"""
	logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")

	parser: argparse.ArgumentParser = buildArgParser()
	args: argparse.Namespace = parser.parse_args()

	addonDirInput: str | None = args.addonDir
	addonDir: str
	if addonDirInput:
		addonDir = os.path.abspath(addonDirInput)
	else:
		cwd: Path = Path(os.getcwd()).resolve()
		addonRoot: Path | None = next((p for p in (cwd, *cwd.parents) if (p / "buildVars.py").exists()), None)
		addonDir = str(addonRoot) if addonRoot is not None else str(cwd)

	logger.info("=== NVDA ADD-ON UPDATE TOOL ===")
	logger.info("Target Directory: %s", addonDir)

	oldBuildvars: str = os.path.join(addonDir, "buildVars.py")

	if not os.path.exists(oldBuildvars):
		logger.error("'%s' does not appear to be a valid NVDA Add-on (missing buildVars.py).", addonDir)
		if sys.stdin.isatty():
			input("\nPress Enter to exit...")
		sys.exit(1)

	logger.info("Phase 1: Analyzing existing project structure and metadata...")
	buildvarsMetadata: dict[str, Any]
	buildvarsMetadata, _ = extractBuildvarsMetadata(oldBuildvars)
	addonName: Any = buildvarsMetadata.get("addon_name", os.path.basename(addonDir))
	logger.info("Target Add-on Identified: %s", addonName)

	if args.dryRun:
		logger.info("RUNNING IN SIMULATION MODE (--dry-run). No files will be modified.")

	logger.info("Phase 2: Safety backup verification...")
	if args.dryRun:
		logger.info("Safety backup skipped (simulation mode active).")
	elif args.skipBackup:
		logger.info("Safety backup skipped (--skip-backup requested by user).")
	else:
		backupDir: str = f"{addonDir}_bak_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
		logger.info("Creating safety automatic backup in: %s...", os.path.basename(backupDir))
		try:
			shutil.copytree(
				addonDir,
				backupDir,
				ignore=shutil.ignore_patterns(".git", "__pycache__", ".venv", "*_bak_*"),
			)
			logger.info("Backup created successfully.")
		except Exception as exceptionObj:
			logger.error("Critical: Backup failed (%s). Aborting update.", exceptionObj)
			if sys.stdin.isatty():
				input("\nPress Enter to exit...")
			sys.exit(1)

	if args.templateDir:
		templatePath: str = os.path.abspath(args.templateDir)
		logger.info("Phase 3: Using local template directory: %s", templatePath)
		if not os.path.exists(os.path.join(templatePath, "buildVars.py")):
			logger.error("Provided template directory does not appear to be a valid NVDA AddonTemplate (missing buildVars.py).")
			if sys.stdin.isatty():
				input("\nPress Enter to exit...")
			sys.exit(1)
		runSynchronization(templatePath, addonDir, args.dryRun)
	else:
		logger.info("Phase 3: Provisioning latest official NVDA AddonTemplate via Git...")
		with tempfile.TemporaryDirectory() as tempDir:
			logger.info("Cloning template into temporary workspace...")
			templateUrl: str = "https://github.com/nvaccess/AddonTemplate.git"

			try:
				subprocess.run(
					["git", "clone", "--depth", "1", templateUrl, tempDir],
					check=True,
					stdout=subprocess.DEVNULL,
					stderr=subprocess.PIPE,
				)
				logger.info("Template cloned successfully.")
			except (subprocess.CalledProcessError, FileNotFoundError) as exceptionObj:
				logger.error("Failed to execute git clone. Make sure Git is available in your PATH.")
				if isinstance(exceptionObj, subprocess.CalledProcessError) and exceptionObj.stderr:
					logger.error("Details: %s", exceptionObj.stderr.decode("utf-8", errors="ignore"))
				if sys.stdin.isatty():
					input("\nPress Enter to exit...")
				sys.exit(1)

			runSynchronization(tempDir, addonDir, args.dryRun)

	if not args.dryRun:
		logger.info("Project successfully updated. Workspace cleared.")
	else:
		logger.info("Simulation finished. Workspace cleared.")


if __name__ == "__main__":
	main()
